#ifndef UNIFIED_WORKLOAD_SIMTRAP_H
#define UNIFIED_WORKLOAD_SIMTRAP_H

#define SIMTRAP_GOOD_TRAP 0x000
#define SIMTRAP_DISABLE_TIME_INTR 0x100
#define SIMTRAP_NOTIFY_PROFILER 0x101
#define SIMTRAP_NOTIFY_WORKLOAD_EXIT 0x102

#define UW_SIMTRAP_STRINGIFY_1(x) #x
#define UW_SIMTRAP_STRINGIFY(x) UW_SIMTRAP_STRINGIFY_1(x)
#define UW_SIMTRAP_HLT(imm) \
    asm volatile("hlt #" UW_SIMTRAP_STRINGIFY(imm) ::: "memory")

#define SIMTRAP_SIGNAL_IMM(imm) UW_SIMTRAP_HLT(imm)
#define SIMTRAP_SIGNAL(imm) SIMTRAP_SIGNAL_IMM(imm)
#define SIMTRAP_PROFILE_START() ((void)0)
#define SIMTRAP_PROFILE_STOP() SIMTRAP_SIGNAL_IMM(SIMTRAP_NOTIFY_WORKLOAD_EXIT)

#endif
